name = "crosshatch-reviewer"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "20"
NEXT_PUBLIC_HOST = "https://reviewer.crosshatch.app"
GITHUB_APP_SLUG = "crosshatch-reviewer"
GITHUB_APP_ID = "1009956"
CROSSHATCH_BASE_URL = "https://api.crosshatch.app/v1"
