import "./globals.css"
import { TailwindIndicator } from "@/components/layout/tailwind-indicator"
import { cn } from "@/lib/utils/cn"
import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"
import type { Metadata } from "next"
import { ThemeProvider } from "next-themes"
import type { PropsWithChildren } from "react"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={cn(
          GeistSans.variable,
          GeistMono.variable,
          "font-sans antialiased"
        )}
      >
        <ThemeProvider attribute="class">
          {children}
          <TailwindIndicator />
        </ThemeProvider>
      </body>
    </html>
  )
}
